### ISSUE TITLE
Login/Logout

### ISSUE THREAD

**Issue by 69ares** [Deadpikle/SimpleInventory#4]
Hello,
after a while that I do not use the program, the logout from the application is forced.
How can I disable it or increase the time that must elapse before logging out?

Thanks

**Comment by Deadpikle** [comment]
Hello!

Thank you for the feature request!

I have added the ability to edit this setting in 0.9.5 (https://github.com/Deadpikle/SimpleInventory/releases/tag/0.9.5).

1. Edit some user to give them Permission to edit app settings. (If you only have yourself in the system, create a new user with full permissions, login as them, then edit yourself. Then you can log back in as yourself and delete the extra user.)
2. Go to the main menu and click "Manage App Settings"
3. Edit the setting for the auto logout timeout. This is in minutes. So, 10 would mean that it auto logs out after 10 minutes. 9999 would mean after 9999 minutes (166 hours). And so on.
4. Save and restart the software for that change to take effect

Enjoy!!

**Comment by Deadpikle** [comment]
When "installing" the new version of the software, make SURE YOU DO NOT OVERWRITE THE `data/inventory.sidb` FILE!!!! Otherwise, you will destroy your data! Otherwise, all other files can be replaced with the download above.
